# Generated by Django 5.1.8 on 2025-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_manual_sent',
            field=models.BooleanField(default=False),
        ),
    ]
