version: '3.9'

services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
