
version: '3.9'

services:
  web:
    build: .
    command: gunicorn auto_text_crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A auto_text_crm worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A auto_text_crm beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://web:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true

  ngrok:
    image: wernight/ngrok
    depends_on:
      - web
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=web:8000
      - NGROK_PROTOCOL=http
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}

