# Generated by Django 5.1.8 on 2025-04-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_lead_phone_lead_customercreatedutc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='CustomerCreatedUTC',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='DoNotCall',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='DoNotEmail',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='DoNotMail',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='LeadCreatedUTC',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='LeadTypeID',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='LeadTypeName',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='SalesPersonFirstName',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='SalesPersonLastName',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='SoldDateUTC',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='VehicleMake',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='VehicleModel',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='VehicleStockNumber',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='VehicleVIN',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='VehicleYear',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='dayphone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='dealerid',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='emailalt',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='evephone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='leadsourcename',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='leadstatustypename',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_interest',
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='message_status',
            field=models.CharField(default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cellphone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('AI', 'AI'), ('Manual', 'Manual')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead')),
            ],
        ),
    ]
