# Generated by Django 5.1.8 on 2025-04-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_lead_customercreatedutc_remove_lead_donotcall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='sent_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
