# Generated by Django 5.1.8 on 2025-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_messagelog_sent_by_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_interest',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
