# Generated by Django 5.1.8 on 2025-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_lead_source_lead_vehicle_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_stage',
            field=models.CharField(default='Day 0', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_texted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
