# Generated by Django 5.1.8 on 2025-04-09 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_lead_follow_up_stage_lead_last_texted_lead_opted_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='CustomerCreatedUTC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='DoNotCall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='DoNotEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='DoNotMail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='LeadCreatedUTC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='LeadTypeID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='LeadTypeName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='SalesPersonFirstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='SalesPersonLastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='SoldDateUTC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='VehicleMake',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='VehicleModel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='VehicleStockNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='VehicleVIN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='VehicleYear',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='dayphone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='dealerid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='emailalt',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='evephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='leadsourcename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='leadstatustypename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='postalcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='salesperson',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='Message',
            name='direction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default='OUT', max_length=10),
        ),
        migrations.AddField(
            model_name='Message',
            name='from_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='Message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='vehicle_interest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='Message',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.lead'),
        ),
        migrations.AlterField(
            model_name='Message',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('Manual', 'Manual'), ('IN', 'Incoming')], max_length=50),
        ),
    ]
