# Generated by Django 5.1.8 on 2025-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_lead_customercreatedutc_lead_donotcall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='message',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('Manual', 'Manual'), ('IN', 'Incoming'), ('System', 'System')], default='Manual', max_length=50),
        ),
    ]
