# Generated by Django 5.1.8 on 2025-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_remove_messagelog_message_messagelog_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
