# Generated by Django 5.2 on 2025-04-17 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_lead_ai_message_count_lead_next_ai_send_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='Message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='lead',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='Message',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='Message',
            name='follow_up_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='Message',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(default='ai_follow_up', max_length=50)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
