# Generated by Django 5.1.8 on 2025-04-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_lead_options_alter_messagelog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
