# Generated by Django 5.2 on 2025-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_active',
            field=models.BooleanField(default=True),
        ),
    ]
