# Generated by Django 5.2 on 2025-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_lead_ai_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='manual_next_ai_send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
