# Generated by Django 5.2 on 2025-04-30 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_lead_manual_next_ai_send_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='CustomerCreatedUTC',
            new_name='customer_created_utc',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='DoNotCall',
            new_name='do_not_call',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='DoNotEmail',
            new_name='do_not_email',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='DoNotMail',
            new_name='do_not_mail',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='LeadCreatedUTC',
            new_name='lead_created_utc',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='LeadTypeName',
            new_name='lead_type_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='SalesPersonFirstName',
            new_name='sales_first',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='SalesPersonLastName',
            new_name='sales_last',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='LeadTypeID',
            new_name='sold_date_utc',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='VehicleMake',
            new_name='vehicle_make',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='VehicleModel',
            new_name='vehicle_model',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='VehicleStockNumber',
            new_name='vehicle_stock_number',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='VehicleVIN',
            new_name='vehicle_vin',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='VehicleYear',
            new_name='vehicle_year',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='SoldDateUTC',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='leadstatustypename',
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_draft_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ai_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='message_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('OUT', 'Outgoing'), ('IN', 'Incoming')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
