# Generated by Django 5.2 on 2025-05-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_customercreatedutc_lead_customer_created_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_ai_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
