# Generated by Django 5.2 on 2025-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_lead_last_ai_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='message',
            name='follow_up_stage',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_number',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_by_ai',
        ),
        migrations.RemoveField(
            model_name='message',
            name='twilio_sid',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.CharField(choices=[('lead', 'Lead'), ('dealer', 'Dealer')], default='dealer', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(default='sms', max_length=50),
        ),
    ]
