# Generated by Django 5.2 on 2025-05-15 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_message_options_rename_content_message_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('OUT', 'Outgoing'), ('IN', 'Incoming')], default='dealer', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='follow_up_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='from_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('Manual', 'Manual'), ('IN', 'Incoming'), ('System', 'System')], default='Manual', max_length=50),
        ),
    ]
