# Generated by Django 5.2 on 2025-05-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_message_options_rename_content_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(default='SMS', max_length=20),
        ),
    ]
